### ISSUE TITLE
資料登録時にS3にPDFを保存する

### ISSUE THREAD

**Issue by ReoYabiku** [ReoYabiku/aloha-hp-next#22]
## 概要
- 書類登録時に、AWS/S3のURLを受け取る仕様ではなく、google documentのIDからS3のURLを自動生成するようにする

### 詳細
書類登録の理想的なフローは以下の通り
1. タイトル、説明文、google document idを入力する
2. google document idをもとに、pdfダウンロードURLにアクセスしてPDFを取得する
3. S3 Clientを利用して、取得したPDFをS3に保存する
4. 保存したpdfへのアクセスURLを取得し、documentsテーブルの`embed_url`に保存する

**Comment by tsunekazuomija** [comment]
現状、httpの500 internal server errorや、fetchでのunexpected json end などのエラーが出る状態です。
今日（9/30）作業できそうにないので、一旦あげておきます。
試すときには、tool.ts内のaccesskeyidとsecretaccesskeyを入力してください。
